create table cargo (
    id         serial primary key,
    name_cargo varchar(16) unique not null
);

create table client (
    id              serial primary key,
    email           varchar(100) unique not null,
    password_client varchar(250)        not null,
    cpf             varchar(16) unique  not null,
    full_name       varchar(100)        not null,
    active          int                 not null,
    id_cargo        int                 not null references cargo (id)
);

create table agency (
    id            serial primary key,
    number_agency int  not null,
    name_agency   text not null
);

create table account (
    id             serial primary key,
    number_account varchar(9) unique            not null,
    balance        numeric check (balance >= 0) not null,
    active         int                          not null,
    id_client      int                          not null references client (id),
    id_agency      int                          not null references agency (id)
);

create table operations (
    id              serial primary key,
    type_operation  int         not null,
    number_account  varchar(10) not null,
    value_operation numeric     not null,
    time_operation  timestamp   not null,
    id_account      int         not null references account (id)
);

INSERT INTO agency(id, number_agency, name_agency)
VALUES (1, 197, 'Stone Pagamentos'),
       (2, 748, 'Banco Cooperativo Sicredi S.A.'),
       (3, 117, 'Advanced Cc Ltda'),
       (4, 077, 'Banco Inter'),
       (5, 735, 'Neon Pagamentos'),
       (6, 340, 'Superdigital'),
       (7, 290, 'PagBank'),
       (8, 121, 'Banco Agibank S.A.'),
       (9, 237, 'Next'),
       (10, 212, 'Banco Original'),
       (11, 260, 'Nubank'),
       (12, 280, 'Banco Willbank'),
       (13, 172, 'Albatross Ccv S.A'),
       (14, 323, 'Mercado Pago'),
       (15, 188, 'Ativa Investimentos S.A'),
       (16, 380, 'PicPay'),
       (17, 280, 'Avista S.A. Crédito, Financiamento e Investimento'),
       (18, 080, 'B&T Cc Ltda'),
       (19, 654, 'Banco A.J.Renner S.A.'),
       (20, 246, 'Banco ABC Brasil S.A.'),
       (21, 75, 'Banco ABN AMRO S.A'),
       (22, 121, 'Banco Agibank S.A.'),
       (23, 25, 'Banco Alfa S.A.'),
       (24, 641, 'Banco Alvorada S.A.'),
       (25, 65, 'Banco Andbank (Brasil) S.A.'),
       (26, 213, 'Banco Arbi S.A.'),
       (27, 96, 'Banco B3 S.A.'),
       (28, 033, 'Banco SANTANDER'),
       (29, 318, 'Banco BMG S.A.'),
       (30, 752, 'Banco BNP Paribas Brasil S.A.'),
       (31, 107, 'Banco BOCOM BBM S.A.'),
       (32, 63, 'Banco Bradescard S.A.'),
       (33, 31, 'Código Banco Beg S.A.'),
       (34, 122, 'Banco Bradesco BERJ S.A.'),
       (35, 204, 'Banco Bradesco Cartões S.A.'),
       (36, 394, 'Banco Bradesco Financiamentos S.A.'),
       (37, 237, 'Banco Bradesco S.A.'),
       (38, 218, 'Banco BS2 S.A.'),
       (39, 208, 'Banco BTG Pactual S.A.'),
       (40, 336, 'Banco C6 S.A – C6 Bank'),
       (41, 473, 'Banco Caixa Geral – Brasil S.A.'),
       (42, 104, 'Banco Caixa Econômica Federal'),
       (43, 412, 'Banco Capital S.A.'),
       (44, 40, 'Banco Cargill S.A.'),
       (45, 368, 'Banco Carrefour'),
       (46, 266, 'Banco Cédula S.A.'),
       (47, 739, 'Banco Cetelem S.A.'),
       (48, 233, 'Banco Cifra S.A.'),
       (49, 745, 'Banco Citibank S.A.'),
       (50, 241, 'Banco Clássico S.A.'),
       (51, 756, 'Banco Cooperativo do Brasil S.A.'),
       (52, 748, 'Banco Cooperativo Sicredi S.A.'),
       (53, 222, 'Banco Credit Agricole Brasil S.A.'),
       (54, 505, 'Banco Credit Suisse (Brasil) S.A.'),
       (55, 69, 'Banco Crefisa S.A.'),
       (56, 3, 'Banco da Amazônia S.A.'),
       (57, 83, 'Banco da China Brasil S.A.'),
       (58, 707, 'Banco Daycoval S.A.'),
       (59, 51, 'Banco de Desenvolvimento do Espírito Santo S.A.'),
       (60, 300, 'Banco de La Nacion Argentina'),
       (61, 495, 'Banco de La Provincia de Buenos Aires'),
       (62, 494, 'Banco de La Republica Oriental del Uruguay'),
       (63, 335, 'Banco Digio S.A'),
       (64, 1, 'Banco do Brasil S.A.'),
       (65, 47, 'Banco do Estado de Sergipe S.A.'),
       (66, 37, 'Banco do Estado do Pará S.A.'),
       (67, 41, 'Banco do Estado do Rio Grande do Sul S.A.'),
       (68, 4, 'Banco do Nordeste do Brasil S.A.'),
       (69, 196, 'Banco Fair Corretora de Câmbio S.A'),
       (70, 265, 'Banco Fator S.A.'),
       (71, 224, 'Banco Fibra S.A.'),
       (72, 626, 'Banco Ficsa S.A.'),
       (73, 94, 'Banco Finaxis S.A.'),
       (74, 612, 'Banco Guanabara S.A.'),
       (75, 12, 'Banco Inbursa S.A.'),
       (76, 604, 'Banco Industrial do Brasil S.A.'),
       (77, 653, 'Banco Indusval S.A.'),
       (78, 77, 'Banco Inter S.A.'),
       (79, 249, 'Banco Investcred Unibanco S.A.'),
       (80, 184, 'Banco Itaú BBA S.A.'),
       (81, 29, 'Banco Itaú Consignado S.A.'),
       (82, 479, 'Banco ItauBank S.A.'),
       (83, 341, 'Banco Itaú'),
       (84, 376, 'Banco J. P. Morgan S.A.'),
       (85, 422, 'Banco Safra'),
       (86, 217, 'Banco John Deere S.A.'),
       (87, 76, 'Banco KDB S.A.'),
       (88, 757, 'Banco KEB HANA do Brasil S.A.'),
       (89, 600, 'Banco Luso Brasileiro S.A.'),
       (90, 243, 'Banco Máxima S.A.'),
       (91, 720, 'Banco Maxinvest S.A.'),
       (92, 389, 'Banco Mercantil do Brasil S.A.'),
       (93, 370, 'Banco Mizuho do Brasil S.A.'),
       (94, 746, 'Banco Modal S.A.'),
       (95, 66, 'Banco Morgan Stanley S.A.'),
       (96, 456, 'Banco MUFG Brasil S.A'),
       (97, 7, 'Banco Nacional de Desenvolvimento Econômico e Social – BNDES');



INSERT INTO cargo(id, name_cargo)
VALUES (1, 'ROLE_ADMIN'),
       (2, 'ROLE_CLIENT');
